#!/usr/bin/env bash

## launch waybar with alt config

CONFIG="$HOME/.config/niri/waybar/config.jsonc"
STYLE="$HOME/.config/niri/waybar/style.css"

kill $(pgrep waybar)
while true; do
    if [[ ! $(pidof waybar) ]]; then
        waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE} &
    fi
    inotifywait -e create,modify $CONFIG $STYLE
    kill $(pgrep waybar)
done
