# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  # clear /tmp on boot to get a stateless /tmp directory.
  boot.tmp.cleanOnBoot = true;

  # Enable binfmt emulation of aarch64-linux, this is required for cross compilation.
  boot.binfmt.emulatedSystems = [
    "aarch64-linux"
    "riscv64-linux"
  ];
  # supported file systems, so we can mount any removable disks with these filesystems
  boot.supportedFilesystems = [
    "ext4"
    "btrfs"
    "xfs"
    "ntfs"
    "fat"
    "vfat"
    "exfat"
  ];
  wsl = {
    enable = true;
    docker-desktop.enable = true;
    startMenuLaunchers = true;
    usbip.enable = true;
    wslConf.boot.systemd = true;
    useWindowsDriver = true;
    wslConf.automount.enabled = true;
    interop.register = true;
  };
  environment.systemPackages = with pkgs; [
    # for mount luks disk from nixos
    cryptsetup
  ];
  programs.nix-ld.enable = true;
  # environment.variables = {
  #   NIX_LD_LIBRARY_PATH = lib.makeLibraryPath [
  #     pkgs.stdenv.cc.cc
  #   ];
  #   NIX_LD = "${pkgs.glibc}/lib/ld-linux-x86-64.so.2";
  # };
  system.stateVersion = "24.11";
}
