#!/usr/bin/env bash
# $HOME/.config/hypr/scripts/recording

ScreenRecordDir="$HOME/Videos/ScreenRecordings"
ProcessInfo="$ScreenRecordDir/process.pid"
WF_RECORDER_OPTS=""
VIDEOEXT="mkv"

if [ "$1" == "status" ];
then
	if [ -f "$ProcessInfo" ];
	then
		awk 'BEGIN{printf "{\"text\":\"\", \"tooltip\":\"Recording\\n"}
		NR==1{printf "PID: %s\\n", $0}
		NR==2{printf "Save to: %s\\n", $0}
		NR==3{printf "Log to: %s\"}", $0}' "$ProcessInfo"
	else
		echo '{"text":"", "tooltip":"Left: FullScreen\nRight: Selection"}'
	fi
	exit
elif [ "$1" == "toggle" ];
then
	if [ -f "$ProcessInfo" ];
	then
		pid=$(cat $ProcessInfo | head -n 1)
		kill -s SIGINT "$pid"
		rm "$ProcessInfo"
	else
		[ -d $ScreenRecordDir ] || mkdir -p "$ScreenRecordDir"
		PrefixOfFiles="$ScreenRecordDir/$(date +'%Y%m%dT%H%M%S')"
		VideoFileName="$PrefixOfFiles.$VIDEOEXT"
		LogFileName="$PrefixOfFiles.log"
		if [ "$2" == "fullscreen" ]; then
			wf-recorder $WF_RECORDER_OPTS -f "$VideoFileName" 1>"$LogFileName" 2>&1 &
		elif [ "$2" == "region" ]; then
			region=$(slurp -b 1B1F2800 -c E06B74ff -s C778DD0D -w 2 -d -o)
			while [ ! -z $(pgrep -x slurp) ]; do wait; done
			wf-recorder $WF_RECORDER_OPTS -g "$region" -f "$VideoFileName" 1>"$LogFileName" 2>&1 &
		else
			printf "Argument %s not valid" "$2"
			exit
		fi
		pid=$(jobs -p | tail -n 1)
		printf "%d\n%s\n%s" "$pid" "$VideoFileName" "$LogFileName" > "$ProcessInfo"
		disown "$pid"
	fi
	exit
else
	printf "Argument %s not valid" "$1"
fi

# https://gist.github.com/raffaem/bb9c35c6aab663efd7a0400c33d248a1
