#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd wayvnc lxpolkit swaybg clash-verge swayidle clash)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Set wallpaper
swaybg --output '*' --mode fill --image ~/.config/wallpapers/default_wallpaper &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
# ~/.config/hypr/scripts/statusbar &
~/.config/hypr/scripts/statusbar_debug &

# Start mpd
exec mpd &

# Start wayvnc
exec wayvnc &

# Start clash-verge
exec clash-verge &

# Start lxpolkit
exec lxpolkit &

exec /nix/store/*xdg-desktop-portal-hyprland*/libexec/xdg-desktop-portal-hyprland &

# Start swayidle
# exec swayidle -w timeout 1800 'systemctl suspend' resume 'hyprctl dispatch dpms on' timeout 120 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock'
exec swayidle -w timeout 120 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock'
