#!/usr/bin/env bash

dir=$(xdg-user-dir VIDEOS)/Aufnahmen

[ -d $dir ] || mkdir -p $dir

file=$dir/$(date +'recording_%Y-%m-%d-%H%M%S.mp4')

echo $file

if [ -z $(pgrep wf-recorder) ]
then
  # do not disturb
  # pkill --signal SIGINT mako
  if [ "$1" == "-s" ]
  then
    notify-send "Record Selection"
    area=$(slurp -b 1B1F2800 -c E06B74ff -s C778DD0D -w 2 -d)
    while [ ! -z $(pgrep -x slurp) ]; do wait; done
    wf-recorder -f $file -a -g "$area" &
  elif [ "$1" == "-w" ]
  then
    slurp -b 00000000 -c 00000000 -s 00000000
    sleep 5
    w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	  w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
    notify-send "Record Window"
    wf-recorder -f $file -a -g "$w_pos $w_size" &
  else
    wf-recorder -f $file -a -g "$(swaymsg -t get_outputs | jq -r '.. | select(.active?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -c "#FFFFFF" )"&
    while [ ! -z $(pgrep -x slurp) ]; do wait; done
  fi
else
  notify-send "Record Output"
  pkill --signal SIGINT wf-recorder
  while [ ! -z $(pgrep -x wf-recorder) ]; do wait; done
  notify-send "Recording Stopped"
  name=$(zenity --entry --text "Enter a filename")

  if [ -n $name ]
  then
    mv $(ls -d $(xdg-user-dir VIDEOS)/Aufnahmen/* -t | head -n1) $(xdg-user-dir VIDEOS)/Aufnahmen/$name.mp4
  fi
fi
