#!/usr/bin/env bash

if pgrep -x wf-recorder >/dev/null; then
  echo '{"text":"On","class":"on","alt":"on"}'
else
  echo '{"text":"Off","class":"off","alt":"off","tooltip": "Left: Selection\nRight: Window\nMiddle: Screen"}'
fi
